# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      pip install praw
      pip install nltk
      pip install pandas
      pip install numpy
      pip install pickle
      pip install matplotlib
    

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
