# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      pip install praw
      pip install nltk
      pip install pandas
      pip install numpy
      pip install pickle
      pip install matplotlib
      pip install yfinance
  - command: python3 -m http.server 8000
    name: webserver
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
   - port: 8000
     onOpen: open-preview
